const CFG={supabase:"https://cishmtektnuvjxyuetvm.supabase.co",key:"sb_publishable_F9lya4xhIKkXcpjhWXvaNg_l-nBZT8g",contest:"https://t.me/CZHUB24Bot?start=contest",links:{telegram:"https://t.me/czhub24",whatsapp:"https://chat.whatsapp.com/G0YbngLJZs62JZ8QLef0mj",viber:"https://invite.viber.com/?g2=AQBEyu%2BkYLoW5lbe0flu%2BPnAUDrUZUpv64chJAs9SWpAFdDAF2TzTHJG0yqUd2xn"}};
const CITIES=[["praha","PRAHA","CZ-10","13 групп","https://commons.wikimedia.org/wiki/Special:FilePath/Prague-Skyline.jpg?width=1400"],["brno","BRNO","CZ-64","9 групп","https://commons.wikimedia.org/wiki/Special:FilePath/Brno%20panorama.jpg?width=1400"],["ostrava","OSTRAVA","CZ-80","7 групп","https://commons.wikimedia.org/wiki/Special:FilePath/Panorama-ostrava.JPG?width=1400"],["plzen","PLZEŇ","CZ-32","6 групп","https://commons.wikimedia.org/wiki/Special:FilePath/Plze%C5%88%20-%20N%C3%A1m%C4%9Bst%C3%AD%20Republiky%20-%20Panorama%20View%20360%C2%B0%2001.jpg?width=1400"],["liberec","LIBEREC","CZ-51","5 групп","https://commons.wikimedia.org/wiki/Special:FilePath/Liberec%20Per%C5%A1t%C3%BDn%20od%20Je%C5%99%C3%A1bu%201.jpg?width=1400"],["hradec-kralove","HRADEC KRÁLOVÉ","CZ-52","5 групп","https://commons.wikimedia.org/wiki/Special:FilePath/Pohled%20z%20n%C3%A1m%C4%9Bst%C3%AD%20Jana%20Pavla%20II.%20panoramic.jpg?width=1400"],["pardubice","PARDUBICE","CZ-53","4 группы","https://commons.wikimedia.org/wiki/Special:FilePath/Pardubick%C3%BD%20z%C3%A1mek%20-%20panorama.JPG?width=1400"],["olomouc","OLOMOUC","CZ-71","4 группы","https://commons.wikimedia.org/wiki/Special:FilePath/Olomouc%20panorama.jpg?width=1400"],["karlovy-vary","KARLOVY VARY","CZ-41","3 группы","https://commons.wikimedia.org/wiki/Special:FilePath/Karlovy%20Vary%20Panorama%20%28135669935%29.jpeg?width=1400"],["ceske-budejovice","ČESKÉ BUDĚJOVICE","CZ-31","4 группы","https://commons.wikimedia.org/wiki/Special:FilePath/%C4%8Cesk%C3%A9%20Bud%C4%9Bjovice%20-%20panoramio%20%281%29.jpg?width=1400"],["usti-nad-labem","ÚSTÍ NAD LABEM","CZ-42","3 группы","https://commons.wikimedia.org/wiki/Special:FilePath/%C3%9Ast%C3%AD%20nad%20Labem%20panorama.jpg?width=1400"],["zlin","ZLÍN","CZ-72","4 группы","https://commons.wikimedia.org/wiki/Special:FilePath/Zlin%20banner.jpg?width=1400"],["jihlava","JIHLAVA","CZ-63","3 группы","https://commons.wikimedia.org/wiki/Special:FilePath/Jihlava%20-%20panoramio.jpg?width=1400"]];
const CATS=[["work","РАБОТА / ВАКАНСИИ","Свежие вакансии и работодатели по городам Чехии.","https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=1400&q=80"],["gigs","ФУШКИ / ПОДРАБОТКИ","Разовые смены, быстрые подработки и фушки.","https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=80"],["rent","АРЕНДА / ЖИЛЬЁ","Квартиры, комнаты, подселение и жильё.","https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1400&q=80"],["market","МАРКЕТ / КУПЛЮ-ПРОДАМ","Товары, техника, вещи и объявления.","https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=1400&q=80"],["auto","АВТО","Покупка, продажа, ремонт и автосервисы.","https://images.unsplash.com/photo-1493238792000-8113da705763?auto=format&fit=crop&w=1400&q=80"],["services","УСЛУГИ","Мастера, ремонт, перевозки, красота и другие услуги.","https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=1400&q=80"],["documents","ДОКУМЕНТЫ","Оформление, переводы, консультации и помощь.","https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1400&q=80"],["community","ОБЩЕНИЕ / ЗНАКОМСТВА","Городские сообщества и новые знакомства.","https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=1400&q=80"],["events","СОБЫТИЯ / ТУСОВКИ","Мероприятия, концерты, встречи и досуг.","https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=1400&q=80"],["health","ЗДОРОВЬЕ / ВРАЧИ","Специалисты, клиники и полезная информация.","https://images.unsplash.com/photo-1538108149393-fbbd81895907?auto=format&fit=crop&w=1400&q=80"],["education","ОБУЧЕНИЕ / ЯЗЫКИ","Курсы, школы, преподаватели и языки.","https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1400&q=80"]];
let state=JSON.parse(localStorage.getItem("czhub24_state")||'{"city":null,"cat":null}');
let pendingCat=null,focusCat=0;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function session(){let x=localStorage.getItem("czhub24_session");if(!x){x=crypto.randomUUID?crypto.randomUUID():"s-"+Date.now();localStorage.setItem("czhub24_session",x)}return x}
function source(){let p=new URLSearchParams(location.search);return p.get("src")||p.get("utm_source")||"direct"}
async function track(type,data={}){try{await fetch(CFG.supabase+"/rest/v1/analytics_events",{method:"POST",headers:{apikey:CFG.key,Authorization:"Bearer "+CFG.key,"Content-Type":"application/json",Prefer:"return=minimal"},body:JSON.stringify({data:{type,sessionId:session(),source:source(),...data}})})}catch(e){}}
function save(){localStorage.setItem("czhub24_state",JSON.stringify(state));$("#crumbCity").textContent=state.city?.name||"ГОРОД";$("#crumbCat").textContent=state.cat?.name||"КАТЕГОРИЯ";$("#choiceBtn").textContent=state.city?(state.city.name+(state.cat?" / "+state.cat.name.split(" / ")[0]:"")):"ВЫБРАТЬ ГОРОД"}
function fx(){let e=$("#fx");e.classList.remove("run");void e.offsetWidth;e.classList.add("run");setTimeout(()=>e.classList.remove("run"),720)}
function openOverlay(id){$("#"+id).classList.add("open");fx()}function closeOverlays(){$$(".overlay").forEach(x=>x.classList.remove("open"))}
function jump(id){closeOverlays();document.getElementById(id).scrollIntoView({behavior:"smooth"})}
function cityOverlay(cat=null){pendingCat=cat;$("#cityOverlayTitle").textContent=cat?cat.name:"ВЫБЕРИ ГОРОД";$("#cityOverlaySub").textContent=cat?"Категория выбрана. Теперь выбери город.":"Сначала выбери город — категории будут следующим шагом.";$("#cityGrid").innerHTML=CITIES.map((c,i)=>`<button data-citypick="${i}"><b>${c[1]}</b><small>${c[2]} · ${c[3]}</small></button>`).join("");openOverlay("cityOverlay")}
function extraOverlay(){$("#extraGrid").innerHTML=CATS.slice(3).map((c,i)=>`<button data-extrapick="${i+3}"><b>${c[1]}</b><small>${c[2]}</small></button>`).join("");openOverlay("extraOverlay")}
function pickCity(i){let c=CITIES[i];state.city={slug:c[0],name:c[1]};track("city_select",{city:c[0]});if(pendingCat){state.cat=pendingCat;track("category_select",{city:c[0],category:pendingCat.slug});save();closeOverlays();showResult()}else{save();closeOverlays();jump("categories")}}
function pickCat(i){let c=CATS[i];state.cat={slug:c[0],name:c[1]};track("category_select",{city:state.city?.slug||null,category:c[0]});save();if(state.city)showResult();else cityOverlay(state.cat)}
function gate(){return new Promise(r=>{let g=$("#gate");$("#gateText").textContent=(state.city?.name||"ВСЯ ЧЕХИЯ")+" × "+(state.cat?.name||"ОСНОВНАЯ ГРУППА");g.classList.add("run");setTimeout(()=>{g.classList.remove("run");r()},2050)})}
async function showResult(){await gate();$("#resultCode").textContent=`CZHUB24 / ${state.city?.name||"ВСЯ ЧЕХИЯ"} / ${state.cat?.name||"ОСНОВНАЯ ГРУППА"}`;$("#resultTitle").innerHTML=`<span>${state.city?.name||"ВСЯ ЧЕХИЯ"}</span><i>×</i><span>${state.cat?.name||"ОСНОВНАЯ ГРУППА"}</span>`;$("#result").classList.add("open")}
function goPlatform(p){let contest=state.cat?.slug==="contest";track(contest?"giveaway_click":"platform_click",{city:state.city?.slug||"all",category:state.cat?.slug||"all",platform:p});location.href=contest&&p==="telegram"?CFG.contest:CFG.links[p]}
function buildCities(){$("#cityRows").innerHTML=CITIES.map((c,i)=>`<div class="cityRow ${i===0?"active":""}" data-city="${i}"><small>[${String(i+1).padStart(3,"0")}]</small><small>${c[2]}</small><b>${c[1]}</b><small>${c[3]} ↗</small></div>`).join("");focusCity(0);$$(".cityRow").forEach(x=>{x.onmouseenter=()=>focusCity(+x.dataset.city);x.onclick=()=>pickCity(+x.dataset.city);if(innerWidth<901)x.style.backgroundImage=`linear-gradient(0deg,#01050a 4%,transparent 78%),url('${CITIES[+x.dataset.city][4]}')`})}
function focusCity(i){let c=CITIES[i];$$(".cityRow").forEach((x,j)=>x.classList.toggle("active",i===j));$("#cityPreview").style.backgroundImage=`url('${c[4]}')`;$("#previewName").textContent=c[1]}
function buildCats(){$("#catList").innerHTML=CATS.map((c,i)=>`<div class="catItem ${i===0?"active":""}" data-catindex="${i}"><small>[${String(i+1).padStart(2,"0")}]</small><b>${c[1]}</b><span>→</span></div>`).join("");focusCategory(0);$$(".catItem").forEach(x=>{x.onmouseenter=()=>focusCategory(+x.dataset.catindex);x.onclick=()=>pickCat(+x.dataset.catindex)})}
function focusCategory(i){focusCat=i;let c=CATS[i];$$(".catItem").forEach((x,j)=>x.classList.toggle("active",i===j));$("#catPreview").style.backgroundImage=`url('${c[3]}')`;$("#catCode").textContent=`${String(i+1).padStart(2,"0")} / CATEGORY`;$("#catName").textContent=c[1];$("#catDesc").textContent=c[2]}
function nodeHover(el,on){let slug=el.dataset.cat,c=CATS.find(x=>x[0]===slug);if(on&&c){$("#coreTitle").textContent=c[1].split(" / ")[0];$("#coreSub").textContent=c[2].toUpperCase().slice(0,38);$("#coreText").textContent="Категория → город → площадка."}else{$("#coreTitle").innerHTML="ВСЯ<br>ЧЕХИЯ";$("#coreSub").textContent="ВЫБЕРИ КАК УДОБНЕЕ";$("#coreText").textContent="Город → категория или категория → город."}}
document.addEventListener("click",e=>{let t=e.target.closest("[data-close]");if(t)closeOverlays();let j=e.target.closest("[data-jump]");if(j)jump(j.dataset.jump);let cp=e.target.closest("[data-citypick]");if(cp)pickCity(+cp.dataset.citypick);let ep=e.target.closest("[data-extrapick]");if(ep){pendingCat={slug:CATS[+ep.dataset.extrapick][0],name:CATS[+ep.dataset.extrapick][1]};closeOverlays();cityOverlay(pendingCat)}});
$$(".node[data-cat]").forEach(n=>{n.onmouseenter=()=>nodeHover(n,true);n.onmouseleave=()=>nodeHover(n,false);n.onclick=()=>{let c=CATS.find(x=>x[0]===n.dataset.cat);pendingCat={slug:c[0],name:c[1]};track("category_select",{category:c[0],city:state.city?.slug||null});cityOverlay(pendingCat)}})
$("#moreCats").onclick=extraOverlay;$("#cityFirst").onclick=()=>cityOverlay();$("#choiceBtn").onclick=()=>cityOverlay();$("#mainGroup").onclick=()=>{state.city={slug:"all",name:"ВСЯ ЧЕХИЯ"};state.cat={slug:"all",name:"ОСНОВНАЯ ГРУППА"};save();showResult()};$("#catSelect").onclick=()=>pickCat(focusCat);$("#menuBtn").onclick=()=>openOverlay("menuOverlay");$("#qrBtn").onclick=()=>{track("share_qr",{source:"share-qr"});openOverlay("qrOverlay")};$("#scrollGroups").onclick=()=>jump("cities");$("#giveBtn").onclick=()=>{track("giveaway_click",{source:"site-giveaway"});location.href=CFG.contest};$("#resultClose").onclick=()=>$("#result").classList.remove("open");$$("[data-dest]").forEach(x=>x.onclick=()=>goPlatform(x.dataset.dest));$$("[data-platform]").forEach(x=>x.onclick=()=>goPlatform(x.dataset.platform));$$("[data-home]").forEach(x=>x.onclick=()=>scrollTo({top:0,behavior:"smooth"}));
addEventListener("scroll",()=>{let max=document.documentElement.scrollHeight-innerHeight;$("#progress").style.width=(max?scrollY/max*100:0)+"%"},{passive:true});
buildCities();buildCats();save();track("page_view",{path:location.pathname+location.search});