(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const extraIcons={documents:'▤',community:'♙',roommates:'♟',moving:'⇄',repairs:'⚒',beauty:'✦',education:'▣',legal:'§',health:'✚',food:'♨',events:'★',sport:'◆','lost-found':'⌖',other:'•••'};
const MAIN_GROUP='https://t.me/czhub24';
function polar(a,r){const x=a*Math.PI/180;return [50+Math.cos(x)*r,50+Math.sin(x)*r]}
function closeExtras(){const m=$('#modal');if(m?.classList.contains('categoryRingModal')){m.hidden=true;m.classList.remove('categoryRingModal')}$('#categoryRow')?.classList.remove('extras-open')}
function ensureHub(){const row=$('#categoryRow');if(!row)return;let hub=$('.czCenterHub',row);if(!hub){hub=document.createElement('button');hub.type='button';hub.className='czCenterHub';hub.innerHTML='<span class="hubMap">✦</span><b>ВСЯ ЧЕХИЯ</b><small>ОСНОВНАЯ ГРУППА</small>';hub.onclick=()=>window.open(MAIN_GROUP,'_blank','noopener,noreferrer');row.append(hub)}return hub}
function enhanceRow(){const row=$('#categoryRow');if(!row)return;const buttons=$$('.catBtn',row);if(buttons.length<7)return;ensureHub();const byId=Object.fromEntries(buttons.map(b=>[b.dataset.category,b]));const ids=['work','gigs','rent','market','auto','services'];const angles=[-90,-30,30,90,150,210];ids.forEach((id,i)=>{const b=byId[id];if(!b)return;const [x,y]=polar(angles[i],36);b.style.setProperty('--wx',x+'%');b.style.setProperty('--wy',y+'%');b.style.setProperty('--delay',(70+i*55)+'ms')});const more=byId.more;if(more){more.style.setProperty('--wx','50%');more.style.setProperty('--wy','67%');more.style.setProperty('--delay','410ms');if(!more.dataset.wheelBound){more.dataset.wheelBound='1';const old=more.onclick;more.onclick=function(e){if(old)old.call(this,e);setTimeout(enhanceExtraRing,0)}}}requestAnimationFrame(()=>row.classList.add('wheel-reveal'))}
function alignExtraRing(){const card=$('.categoryRingModal .modalCard'),base=$('.categorySection');if(!card||!base)return;const r=base.getBoundingClientRect();card.style.left=(r.left+r.width/2)+'px';card.style.top=(r.top+r.height/2)+'px';const size=Math.min(r.width*1.52,innerWidth*.56,innerHeight*.78);card.style.width=size+'px';card.style.height=size+'px'}
function enhanceExtraRing(){const modal=$('#modal'),body=$('#modalBody');if(!modal||!body)return;const extras=$$('[data-extra]',body);if(!extras.length)return;modal.classList.add('categoryRingModal');$('#categoryRow')?.classList.add('extras-open');alignExtraRing();extras.forEach((b,i)=>{const [x,y]=polar(-90+(360/extras.length)*i,45);b.style.setProperty('--ex',x+'%');b.style.setProperty('--ey',y+'%');b.style.setProperty('--delay',(i*24)+'ms');if(!b.querySelector('.extraIco')){const s=document.createElement('span');s.className='extraIco';s.textContent=extraIcons[b.dataset.extra]||'◇';b.prepend(s)}})}
function installBrandIcons(){const svg={telegram:'<svg viewBox="0 0 24 24"><path d="M21.8 3.2 18.7 19c-.2 1.1-.8 1.4-1.7.9l-4.7-3.5-2.3 2.2c-.3.3-.5.5-1 .5l.4-4.8 8.7-7.9c.4-.3-.1-.5-.6-.2L6.8 13 2.1 11.5c-1-.3-1-1 .2-1.5L20.5 3c.8-.3 1.6.2 1.3.2Z"/></svg>',whatsapp:'<svg viewBox="0 0 24 24"><path d="M12 1a11 11 0 0 0-9.5 16.5L1 23l5.7-1.5A11 11 0 1 0 12 1Zm5.8 15.2c-.2.6-1.3 1.2-1.8 1.3-.5.1-1.2.2-3.7-.8-3.1-1.3-5.1-4.4-5.3-4.6-.1-.2-1.2-1.6-1.2-3.1 0-1.5.8-2.2 1.1-2.5.3-.3.6-.4.8-.4h.6c.2 0 .4 0 .6.5l.8 1.9c.1.3.1.5 0 .7l-.5.8c-.2.2-.4.5-.2.8.2.3.8 1.4 1.8 2.2 1.2 1.1 2.2 1.4 2.5 1.6.3.1.5.1.7-.1l1-1.2c.2-.3.5-.2.8-.1l2 .9c.3.1.5.2.6.3.1.2.1.8-.1 1.8Z"/></svg>',viber:'<svg viewBox="0 0 24 24"><path d="M12 1C5.6 1 1.8 3.7 1.5 9.5c-.2 4.6.6 7.8 4.4 9.4v3.4c0 .5.6.8 1 .5l3.6-3h1.6c6.4 0 10.1-2.7 10.4-8.5C22.8 5.3 18.5 1 12 1Zm5 14.7c-.4.8-1.2 1.5-2.1 1.4-1.2-.1-3.4-1.2-5.2-2.8-1.7-1.5-3.3-3.8-3.6-5.3-.2-1 .5-1.8 1.3-2.2.4-.2.7-.1 1 .3l1.1 2c.2.4.1.7-.2 1l-.6.7c.5 1.2 2.3 3 3.6 3.5l.7-.7c.3-.3.6-.4 1-.2l2 .9c.5.2 1.1.7 1 1.4Z"/></svg>'};$$('[data-platform]').forEach(b=>{const p=b.dataset.platform,s=b.querySelector('span');if(s&&svg[p]){s.classList.add('brandIcon');s.innerHTML=svg[p]}})}
function installMessengerStages(){const row=$('.platformRow');if(!row||row.dataset.staged)return;row.dataset.staged='1';const names=[['ПЕРВАЯ СЕКУНДА','Появляется Telegram'],['ВТОРАЯ СЕКУНДА','Появляется WhatsApp'],['ТРЕТЬЯ СЕКУНДА','Появляется Viber']];const buttons=$$('.platform',row);buttons.forEach((b,i)=>{const panel=document.createElement('div');panel.className='messengerStage';panel.innerHTML=`<div class="stageCaption"><strong>${i+1}</strong><span>${names[i][0]}<small>${names[i][1]}</small></span></div><div class="stageVortex"><i></i><i></i><i></i></div>`;row.insertBefore(panel,b);panel.append(b)})}
function revealPlatforms(){closeExtras();installMessengerStages();const panels=$$('.messengerStage');panels.forEach((p,i)=>{p.classList.remove('run');p.style.setProperty('--stage-delay',`${i}s`);void p.offsetWidth;p.classList.add('run')})}
function init(){installBrandIcons();installMessengerStages();enhanceRow();$('#cityLayer')?.addEventListener('click',e=>{if(e.target.closest('.cityNode')){const r=$('#categoryRow');r?.classList.remove('wheel-reveal');setTimeout(()=>r?.classList.add('wheel-reveal'),40)}});$('#categoryRow')?.addEventListener('click',e=>{const b=e.target.closest('.catBtn');if(b&&!b.classList.contains('more'))closeExtras()});const row=$('#categoryRow');if(row)new MutationObserver(enhanceRow).observe(row,{childList:true});const app=$('#app');if(app)new MutationObserver(()=>{if(app.classList.contains('step-platform'))setTimeout(revealPlatforms,20)}).observe(app,{attributes:true,attributeFilter:['class']});const modal=$('#modal');if(modal)new MutationObserver(()=>{if(modal.hidden){modal.classList.remove('categoryRingModal');$('#categoryRow')?.classList.remove('extras-open')}else setTimeout(enhanceExtraRing,0)}).observe(modal,{attributes:true,attributeFilter:['hidden']});const body=$('#modalBody');if(body)new MutationObserver(()=>setTimeout(enhanceExtraRing,0)).observe(body,{childList:true,subtree:true});addEventListener('resize',()=>{if($('#modal')?.classList.contains('categoryRingModal'))alignExtraRing()},{passive:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();