const URL='https://cishmtektnuvjxyuetvm.supabase.co';
const KEY='sb_publishable_F9lya4xhIKkXcpjhWXvaNg_l-nBZT8g';
const $=s=>document.querySelector(s); let token=null;
async function api(path,opt={}){const r=await fetch(URL+path,{...opt,headers:{apikey:KEY,Authorization:`Bearer ${token||KEY}`,'Content-Type':'application/json',...(opt.headers||{})}});const text=await r.text();let data;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok)throw new Error(data?.msg||data?.message||data?.error_description||text||`HTTP ${r.status}`);return data}
function saveSession(s){token=s?.access_token||null;if(s)localStorage.setItem('cz_admin_session',JSON.stringify(s));else localStorage.removeItem('cz_admin_session')}
function restore(){try{const s=JSON.parse(localStorage.getItem('cz_admin_session'));if(s?.access_token&&s?.expires_at*1000>Date.now()){token=s.access_token;return true}}catch{}return false}
async function login(e){e.preventDefault();$('#loginMsg').textContent='Вход…';try{const s=await api('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email:$('#email').value,password:$('#password').value})});saveSession(s);showDash();await load()}catch(err){$('#loginMsg').textContent='Ошибка входа: '+err.message}}
function showDash(){ $('#login').hidden=true;$('#dash').hidden=false }
function logout(){saveSession(null);$('#dash').hidden=true;$('#login').hidden=false;$('#password').value=''}
function renderList(id,arr=[]){const el=$(id);if(!arr.length){el.innerHTML='<div class="muted">Пока нет данных</div>';return}const max=Math.max(...arr.map(x=>Number(x.count)||0),1);el.innerHTML=arr.slice(0,12).map(x=>`<div class="row"><span>${esc(x.name||'—')}</span><div class="bar"><i style="width:${Math.max(2,(Number(x.count)||0)/max*100)}%"></i></div><strong>${Number(x.count)||0}</strong></div>`).join('')}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function load(){const days=Number($('#period').value);$('#status').textContent='Обновление…';try{const d=await api('/rest/v1/rpc/czhub24_dashboard',{method:'POST',body:JSON.stringify({days_back:days})});$('#sessions').textContent=d.sessions??0;$('#outbound').textContent=d.outbound??0;$('#conversion').textContent=(d.conversion??0)+'%';$('#giveaway').textContent=d.giveaway??0;renderList('#cities',d.cities);renderList('#categories',d.categories);renderList('#platforms',d.platforms);renderList('#sources',d.sources);const c=$('#combinations');c.innerHTML=(d.combinations||[]).slice(0,15).map((x,i)=>`<div class="combo"><span>${i<3?'★ ':''}${esc(x.city)} → ${esc(x.category)}</span><b>${x.count}</b></div>`).join('')||'<div class="muted">Пока нет данных</div>';$('#status').textContent='Обновлено: '+new Date().toLocaleTimeString()}catch(err){$('#status').textContent='Ошибка: '+err.message;if(/jwt|token|unauthorized/i.test(err.message))logout()}}
$('#loginForm').addEventListener('submit',login);$('#logout').onclick=logout;$('#refresh').onclick=load;$('#period').onchange=load;if(restore()){showDash();load()}
